// models/AttendanceModel.js
const mongoose = require('mongoose');

const attendanceSchema = new mongoose.Schema({
  employee: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'User', 
    required: true,
    index: true
  },
    employeeId: {
    type: String, 
  },
    calculatedStatus: {  // ✅ এই ফিল্ড যোগ করুন
    type: String,
    enum: ['Present', 'Late', 'Early'],
    default: 'Present'
  },
  lateEarlyDetails: {  // ✅ এই ফিল্ড যোগ করুন
    differenceMinutes: Number,
    lateThreshold: { type: Number, default: 5 },
    earlyThreshold: { type: Number, default: -1 },
    calculatedAt: Date
  },
  date: { 
    type: Date, 
    required: true,
    index: true 
  },
  clockIn: { 
    type: Date 
  },
  clockOut: { 
    type: Date 
  },
  totalHours: { 
    type: Number, 
    default: 0,
    min: 0,
    max: 48 // Increased to support night shifts (up to 48 hours)
  },
  status: { 
    type: String, 
    enum: ['Present', 'Absent', 'Leave', 'Govt Holiday', 'Weekly Off', 'Off Day', 'Late', 'Clocked In', 'Half Day', 'Early', 'Unpaid Leave', 'Half Paid Leave'], 
    default: 'Absent' 
  },

    // Onsite attendance flag (NEW)
  isOnsite: {
    type: Boolean,
    default: function() {
      // এই field auto-populate হবে employee data থেকে
      // আমরা controller-এ populate করব
      return false;
    }
  },
  
  // Location tracking (optional)
  clockInLocation: {
    type: String,
    default: ''
  },
  clockOutLocation: {
    type: String,
    default: ''
  },
  
  // Approval
  approvedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  approvedAt: {
    type: Date
  },
  isApproved: {
    type: Boolean,
    default: false
  },
  
  notes: {
    type: String,
    default: ''
  },
 
  // Ensure your model has these fields:
autoGenerated: {
  type: Boolean,
  default: false
},
markedAbsent: {
  type: Boolean,
  default: false
},
absentMarkedAt: {
  type: Date
},
autoMarked: {
  type: Boolean,
  default: false
},
  // Shift Details (employee specific)
  shift: {
    type: {
      name: { type: String, default: 'Regular' },
      start: { type: String, default: '09:00' },
      end: { type: String, default: '18:00' },
      lateThreshold: { type: Number, default: 5 },
      earlyThreshold: { type: Number, default: -1 },
      autoClockOutDelay: { type: Number, default: 10 },
      isNightShift: { type: Boolean, default: false } // Added night shift flag
    },
    default: {
      name: "Regular",
      start: "09:00",
      end: "18:00",
      lateThreshold: 5,
      earlyThreshold: -1,
      autoClockOutDelay: 10,
      isNightShift: false
    }
  },
  
  // Late/Early Calculation
  lateMinutes: {
    type: Number,
    default: 0
  },
  earlyMinutes: {
    type: Number,
    default: 0
  },
  isLate: {
    type: Boolean,
    default: false
  },
  isEarly: {
    type: Boolean,
    default: false
  },
  
  // Auto Operations
  autoClockOut: {
    type: Boolean,
    default: false
  },
  autoClockOutTime: {
    type: String
  },
  autoClockOutIsNextDay: { // Added for night shift auto clock out
    type: Boolean,
    default: false
  },
  autoMarked: {
    type: Boolean,
    default: false
  },
  markedAbsent: {
    type: Boolean,
    default: false
  },
  absentMarkedAt: {
    type: Date
  },
  
  // Location and Device
  ipAddress: { 
    type: String 
  },
  device: { 
    type: Object 
  },
  location: {
    type: String
  },
  
  // Admin operations
  correctedByAdmin: { 
    type: Boolean, 
    default: false 
  },
  correctedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  correctionDate: {
    type: Date
  },
  correctionReason: {
    type: String
  },
  
  // Admin adjusted shift
  adminAdjustedShift: {
    type: Boolean,
    default: false
  },
  adminShiftAdjustment: {
    start: String,
    end: String,
    lateThreshold: Number,
    earlyThreshold: Number,
    autoClockOutDelay: Number,
    isNightShift: { type: Boolean, default: false }, // Added
    adjustedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    adjustmentDate: Date,
    reason: String
  },
  
  // Leave reference (if applicable)
  leaveId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Leave'
  },
  leavePayStatus: {
    type: String,
    enum: ['Paid', 'Unpaid', 'HalfPaid', null],
    default: null
  },
  
  // Overtime
  overtimeHours: {
    type: Number,
    default: 0
  },
  
  // Night shift specific fields
  nightShiftAdjustment: { // Track if night shift crosses midnight
    type: {
      clockInDayOffset: { type: Number, default: 0 },
      clockOutDayOffset: { type: Number, default: 0 },
      totalDays: { type: Number, default: 1 }
    }
  },
  
  remarks: {
    type: String
  },
  
  // Status flags
  isActive: {
    type: Boolean,
    default: true
  },
  
  // Auto generated flag
  autoGenerated: {
    type: Boolean,
    default: false
  },
  
  // Soft delete
  isDeleted: {
    type: Boolean,
    default: false
  },
  deletedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  deletedAt: {
    type: Date
  }
}, { 
  timestamps: true 
});

// Indexes
attendanceSchema.index({ 
  employee: 1, 
  date: 1 
}, { 
  unique: true,
  partialFilterExpression: { isDeleted: false }
});
attendanceSchema.index({ date: 1, status: 1 });
attendanceSchema.index({ employee: 1, status: 1 });
attendanceSchema.index({ isLate: 1 });
attendanceSchema.index({ autoClockOut: 1 });
attendanceSchema.index({ 
  date: 1, 
  autoGenerated: 1 
});

// Add index for markedAbsent
attendanceSchema.index({ 
  date: 1, 
  markedAbsent: 1 
});
attendanceSchema.index({ isDeleted: 1 });
attendanceSchema.index({ "shift.isNightShift": 1 }); // Added index for night shift
attendanceSchema.index({ date: 1, "shift.isNightShift": 1 }); // Added combined index

// Pre-save middleware to calculate hours (updated for night shifts)
// Pre-save middleware to prevent duplicates
attendanceSchema.pre('save', async function(next) {
  // Skip for deleted records
  if (this.isDeleted) return next();
  
  // Check for existing record with same employee and date
  try {
    const existingRecord = await this.constructor.findOne({
      employee: this.employee,
      date: this.date,
      isDeleted: false,
      _id: { $ne: this._id } // Exclude current document if updating
    });
    
    if (existingRecord) {
      const error = new Error(`Attendance record already exists for this employee on ${this.date}`);
      error.code = 'DUPLICATE_ATTENDANCE';
      return next(error);
    }
  } catch (error) {
    return next(error);
  }
  
  // Calculate hours
  if (this.clockIn && this.clockOut) {
    const diffMs = this.clockOut - this.clockIn;
    const hours = parseFloat((diffMs / (1000 * 60 * 60)).toFixed(4));
    
    if (hours < 0) {
      this.totalHours = hours + 24;
      if (!this.nightShiftAdjustment) {
        this.nightShiftAdjustment = {
          clockInDayOffset: 0,
          clockOutDayOffset: 1,
          totalDays: 2
        };
      }
    } else {
      this.totalHours = hours;
    }
  }
  next();
});

// Virtual for formatted date
attendanceSchema.virtual('formattedDate').get(function() {
  return this.date.toISOString().split('T')[0];
});

// Virtual for night shift duration
attendanceSchema.virtual('nightShiftDuration').get(function() {
  if (!this.shift.isNightShift) return null;
  
  const startMinutes = this.convertTimeToMinutes(this.shift.start);
  const endMinutes = this.convertTimeToMinutes(this.shift.end);
  
  if (endMinutes < startMinutes) {
    // Night shift crossing midnight
    return (24 * 60) - startMinutes + endMinutes;
  }
  
  return endMinutes - startMinutes;
});

// Method to check if attendance is working day
attendanceSchema.methods.isWorkingDay = function() {
  const nonWorkingStatuses = ['Govt Holiday', 'Weekly Off', 'Off Day', 'Leave', 'Unpaid Leave', 'Half Paid Leave'];
  return !nonWorkingStatuses.includes(this.status);
};

// Method to check if it's a night shift day
attendanceSchema.methods.isNightShiftDay = function() {
  return this.shift.isNightShift || false;
};

// Helper method to convert time string to minutes
attendanceSchema.methods.convertTimeToMinutes = function(timeStr) {
  if (!timeStr) return 0;
  const [hours, minutes] = timeStr.split(':').map(Number);
  return hours * 60 + minutes;
};

// Method to get effective clock out time considering night shift
attendanceSchema.methods.getEffectiveClockOutTime = function() {
  if (!this.clockOut) return null;
  
  const clockOut = new Date(this.clockOut);
  
  // If night shift and clock out is before shift start (e.g., clock out at 02:00 AM for 20:00-04:00 shift)
  if (this.shift.isNightShift) {
    const shiftStartMinutes = this.convertTimeToMinutes(this.shift.start);
    const clockOutMinutes = clockOut.getHours() * 60 + clockOut.getMinutes();
    
    if (clockOutMinutes < shiftStartMinutes) {
      // Clock out is on next day
      const nextDay = new Date(clockOut);
      nextDay.setDate(nextDay.getDate() + 1);
      return nextDay;
    }
  }
  
  return clockOut;
};

// Method to get effective clock in time considering night shift
attendanceSchema.methods.getEffectiveClockInTime = function() {
  if (!this.clockIn) return null;
  
  const clockIn = new Date(this.clockIn);
  
  // If night shift and clock in is before shift end (e.g., clock in at 02:00 AM for 20:00-04:00 shift)
  if (this.shift.isNightShift) {
    const shiftEndMinutes = this.convertTimeToMinutes(this.shift.end);
    const clockInMinutes = clockIn.getHours() * 60 + clockIn.getMinutes();
    
    if (clockInMinutes < shiftEndMinutes) {
      // Clock in is on next day relative to shift start
      const prevDay = new Date(clockIn);
      prevDay.setDate(prevDay.getDate() - 1);
      return prevDay;
    }
  }
  
  return clockIn;
};

// Method to check if should auto clock out (considering night shift)
attendanceSchema.methods.shouldAutoClockOut = function(currentTime) {
  if (!this.clockIn || this.clockOut || this.autoClockOut) {
    return false;
  }
  
  const now = currentTime || new Date();
  const nowMinutes = now.getHours() * 60 + now.getMinutes();
  const autoClockOutMinutes = this.convertTimeToMinutes(this.autoClockOutTime);
  
  // If auto clock out is on next day
  if (this.autoClockOutIsNextDay) {
    // Add 24 hours for comparison
    const autoClockOutNextDay = autoClockOutMinutes + (24 * 60);
    
    // Check if current time is after auto clock out time on next day
    const currentDayMinutes = nowMinutes;
    return currentDayMinutes >= autoClockOutMinutes || 
           (nowMinutes < autoClockOutMinutes && autoClockOutNextDay <= nowMinutes + (24 * 60));
  }
  
  return nowMinutes >= autoClockOutMinutes;
};

// Static method to find pending night shift attendances
attendanceSchema.statics.findPendingNightShiftAttendances = function(date) {
  const today = new Date(date);
  today.setHours(0, 0, 0, 0);
  
  return this.find({
    date: today,
    'shift.isNightShift': true,
    clockIn: { $exists: true, $ne: null },
    clockOut: { $exists: false },
    isDeleted: false,
    autoClockOut: { $ne: true }
  });
};

// Static method to find night shift attendances by date range
attendanceSchema.statics.findNightShiftAttendances = function(startDate, endDate, employeeId = null) {
  const query = {
    date: { $gte: startDate, $lte: endDate },
    'shift.isNightShift': true,
    isDeleted: false
  };
  
  if (employeeId) {
    query.employee = employeeId;
  }
  
  return this.find(query);
};

// Export the model
module.exports = mongoose.models.Attendance || mongoose.model('Attendance', attendanceSchema);