// models/PayrollModel.js
const mongoose = require('mongoose');

const payrollSchema = new mongoose.Schema({
  employee: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  
  name: {
    type: String,
    required: true
  },
  
  periodStart: {
    type: Date,
    required: true
  },
  
  periodEnd: {
    type: Date,
    required: true
  },
  
  // Calculation Details
  basicPay: {
    type: Number,
    required: true,
    min: 0
  },
  
  presentDays: {
    type: Number,
    default: 0
  },
  
  totalWorkingDays: {
    type: Number,
    default: 26
  },
  
  attendancePercentage: {
    type: Number,
    default: 0
  },
  
  leaveDays: {
    type: Number,
    default: 0
  },
  
  totalAddition: {
    type: Number,
    default: 0
  },
  
  totalDeduction: {
    type: Number,
    default: 0
  },
  
  netPayable: {
    type: Number,
    required: true,
    min: 0
  },
  
  // Status
  status: {
    type: String,
    enum: ['Pending', 'Paid', 'Rejected', 'Processing'],
    default: 'Pending'
  },
  
  employeeApproved: {
    type: Boolean,
    default: false
  },
  
  employeeApprovedAt: Date,
  
  paymentDate: Date,
  
  rejectionReason: String,
  
  // Auto Generation Details
  autoGenerated: {
    type: Boolean,
    default: false
  },
  
  generatedOn: Date,
  
  // Calculation Details
  calculationDetails: mongoose.Schema.Types.Mixed,
  
  rulesApplied: {
    salaryRuleId: mongoose.Schema.Types.ObjectId,
    ruleName: String,
    calculationMethod: String
  },
  
  calculatedDate: {
    type: Date,
    default: Date.now
  },
  
  notes: String,
  
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  
  createdAt: {
    type: Date,
    default: Date.now
  },
  
  updatedAt: {
    type: Date,
    default: Date.now
  }
});

// Update timestamp
payrollSchema.pre('save', function(next) {
  this.updatedAt = Date.now();
  next();
});

// Index for faster queries
payrollSchema.index({ employee: 1, periodStart: -1 });
payrollSchema.index({ status: 1 });
payrollSchema.index({ autoGenerated: 1 });

const Payroll = mongoose.model('Payroll', payrollSchema);
module.exports = Payroll;